[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
uniswap_clone = "EYZmnDZqskkz4GcvTU4t5dUPaMwRSgpEX43856gpK1e9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\kaush\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
